#!/bin/bash
# Session summary generator (LEGACY — not registered in hooks)
# Superseded by on-session-stop.sh + update-metrics.sh pipeline
# Kept for reference only — do NOT add to on-session-stop.sh

# Configuration
MEMORY_DIR=".claude/memory"
PROGRESS_FILE="$MEMORY_DIR/progress.json"
METRICS_FILE="$MEMORY_DIR/llm-usage.json"
CONTEXT_FILE="$MEMORY_DIR/active-context.json"
SUMMARY_FILE=".claude/SESSION_SUMMARY.md"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo ""
echo "═══════════════════════════════════════════════════════"
echo "📊 SESSION SUMMARY"
echo "═══════════════════════════════════════════════════════"

# Get timestamp
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
echo "Session ended: $TIMESTAMP"

# Count tasks
if [ -f "$PROGRESS_FILE" ]; then
    COMPLETED=$(jq '[.tasks[] | select(.status=="completed")] | length' "$PROGRESS_FILE" 2>/dev/null || echo 0)
    TOTAL=$(jq '.tasks | length' "$PROGRESS_FILE" 2>/dev/null || echo 0)
    echo "Tasks: $COMPLETED completed out of $TOTAL total"
fi

# Check for triviality scores
if [ -f "$PROGRESS_FILE" ]; then
    TRIVIAL=$(jq '[.tasks[] | select(.triviality.score >= 4)] | length' "$PROGRESS_FILE" 2>/dev/null || echo 0)
    if [ "$TRIVIAL" -gt 0 ]; then
        echo "Triviality detections: $TRIVIAL tasks flagged for manual"
    fi
fi

# Check for loops
if [ -f "$PROGRESS_FILE" ]; then
    LOOPS=$(jq '[.tasks[] | select(.status=="blocked" and .loopRisk=="red")] | length' "$PROGRESS_FILE" 2>/dev/null || echo 0)
    if [ "$LOOPS" -gt 0 ]; then
        echo "Loops detected: $LOOPS escalated to Critic"
    fi
fi

# Token tracking
if [ -f "$METRICS_FILE" ]; then
    TOKENS=$(jq '.metadata.totalTokens // 0' "$METRICS_FILE" 2>/dev/null || echo 0)
    SESSIONS=$(jq '.metadata.totalEntries // 0' "$METRICS_FILE" 2>/dev/null || echo 0)
    if [ "$TOKENS" -gt 0 ]; then
        echo "Tokens used this session: ~$TOKENS"
        if [ "$SESSIONS" -gt 1 ]; then
            AVG=$(jq '.metadata.avgTokensPerEntry // 0' "$METRICS_FILE" 2>/dev/null)
            echo "Average per task: ~$AVG tokens"
        fi
    fi
fi

echo ""
echo "═══════════════════════════════════════════════════════"

# Generate detailed summary
generate_summary() {
    cat > "$SUMMARY_FILE" << EOF
# Session Summary — $TIMESTAMP

## Metrics
- **Completed tasks:** $COMPLETED
- **Total tasks:** $TOTAL
- **Tokens used:** ~$TOKENS
- **Session count:** $SESSIONS

## Safety gates activated
$(
    if [ "$TRIVIAL" -gt 0 ]; then
        echo "- Triviality detector: $TRIVIAL suggestions"
    fi
    if [ "$LOOPS" -gt 0 ]; then
        echo "- Loop detection: $LOOPS escalations"
    fi
)

## Next session recommendations

Based on progress:
- Check blocked tasks in .claude/memory/progress.json
- Review escalations to Critic
- Continue with pending tasks

## Files changed
\`\`\`bash
# View recent changes:
git log --oneline -5

# View diff since last commit:
git diff HEAD
\`\`\`

## Memory status
\`\`\`bash
# Check memory files:
ls -lh .claude/memory/
wc -l .claude/memory/*.json
\`\`\`

Generated: $TIMESTAMP
Auto-generated by on-session-stop-summary.sh

EOF
    echo -e "${GREEN}✅ Summary saved to $SUMMARY_FILE${NC}"
}

# Generate summary if memory file exists
if [ -f "$PROGRESS_FILE" ]; then
    generate_summary
fi

echo ""
echo "🎉 Session complete!"
echo ""
