# PAQUETES EL CLUB v1.0 - ALEMBIC SCRIPT TEMPLATE
# Template para generar archivos de migración

"""make_s3_fields_nullable_in_file_uploads

Revision ID: a5d463fb8a42
Revises: 1d474fa1a710
Create Date: 2025-10-01 16:18:16.789277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5d463fb8a42'
down_revision = '1d474fa1a710'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_name')
    )
    op.create_table('rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_type', sa.Enum('STORAGE', 'DELIVERY', 'PACKAGE_TYPE', name='ratetype'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('daily_storage_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('package_type_multiplier', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rates_is_active'), 'rates', ['is_active'], unique=False)
    op.create_index(op.f('ix_rates_rate_type'), 'rates', ['rate_type'], unique=False)
    op.create_table('report_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.Enum('PACKAGES_SUMMARY', 'CUSTOMERS_ANALYSIS', 'REVENUE_REPORT', 'PERFORMANCE_METRICS', 'SMS_ANALYTICS', 'MESSAGES_REPORT', 'CUSTOM_REPORT', name='reporttype'), nullable=False),
    sa.Column('default_parameters', sa.JSON(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.Enum('PACKAGES_SUMMARY', 'CUSTOMERS_ANALYSIS', 'REVENUE_REPORT', 'PERFORMANCE_METRICS', 'SMS_ANALYTICS', 'MESSAGES_REPORT', 'CUSTOM_REPORT', name='reporttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='reportstatus'), nullable=True),
    sa.Column('format', sa.Enum('PDF', 'EXCEL', 'CSV', 'JSON', 'HTML', name='reportformat'), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.Enum('PACKAGES_SUMMARY', 'CUSTOMERS_ANALYSIS', 'REVENUE_REPORT', 'PERFORMANCE_METRICS', 'SMS_ANALYTICS', 'MESSAGES_REPORT', 'CUSTOM_REPORT', name='reporttype'), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_config', sa.JSON(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('package_history')
    op.alter_column('customers', 'address_country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'Colombia'::character varying"))
    op.alter_column('customers', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('customers', 'is_vip',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('customers', 'total_packages_received',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'total_packages_delivered',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'total_spent',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('customers_document_number_key', 'customers', type_='unique')
    op.drop_constraint('customers_phone_key', 'customers', type_='unique')
    op.create_index(op.f('ix_customers_document_number'), 'customers', ['document_number'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_first_name'), 'customers', ['first_name'], unique=False)
    op.create_index(op.f('ix_customers_full_name'), 'customers', ['full_name'], unique=False)
    op.create_index(op.f('ix_customers_is_active'), 'customers', ['is_active'], unique=False)
    op.create_index(op.f('ix_customers_is_vip'), 'customers', ['is_vip'], unique=False)
    op.create_index(op.f('ix_customers_last_name'), 'customers', ['last_name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=True)
    op.alter_column('file_uploads', 's3_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('file_uploads', 's3_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('notifications', 'event_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PACKAGE_ANNOUNCED', 'PACKAGE_RECEIVED', 'PACKAGE_DELIVERED', 'PACKAGE_CANCELLED', 'PAYMENT_DUE', 'CUSTOM_MESSAGE', name='notificationevent'),
               nullable=False,
               existing_server_default=sa.text("'CUSTOM_MESSAGE'::character varying"))
    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'),
               nullable=False,
               existing_server_default=sa.text("'NORMAL'::character varying"))
    op.alter_column('notifications', 'recipient',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('notifications', 'cost_cents',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('notifications', 'is_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'is_test',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.create_foreign_key(None, 'notifications', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'package_announcements_new', ['announcement_id'], ['id'])
    op.create_foreign_key(None, 'package_announcements_new', 'packages', ['package_id'], ['id'])
    op.create_foreign_key(None, 'package_announcements_new', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'package_announcements_new', 'users', ['created_by_id'], ['id'])
    op.alter_column('packages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('packages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_packages_id', table_name='packages')
    op.create_foreign_key(None, 'sms_configuration', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'sms_message_templates', 'users', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'sms_message_templates', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sms_message_templates', type_='foreignkey')
    op.drop_constraint(None, 'sms_message_templates', type_='foreignkey')
    op.drop_constraint(None, 'sms_configuration', type_='foreignkey')
    op.create_index('ix_packages_id', 'packages', ['id'], unique=False)
    op.alter_column('packages', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('packages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'package_announcements_new', type_='foreignkey')
    op.drop_constraint(None, 'package_announcements_new', type_='foreignkey')
    op.drop_constraint(None, 'package_announcements_new', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_test',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'is_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'max_retries',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('notifications', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'cost_cents',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('notifications', 'recipient',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('notifications', 'priority',
               existing_type=sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'NORMAL'::character varying"))
    op.alter_column('notifications', 'event_type',
               existing_type=sa.Enum('PACKAGE_ANNOUNCED', 'PACKAGE_RECEIVED', 'PACKAGE_DELIVERED', 'PACKAGE_CANCELLED', 'PAYMENT_DUE', 'CUSTOM_MESSAGE', name='notificationevent'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'CUSTOM_MESSAGE'::character varying"))
    op.alter_column('file_uploads', 's3_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('file_uploads', 's3_key',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_last_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_vip'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_active'), table_name='customers')
    op.drop_index(op.f('ix_customers_full_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_first_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_document_number'), table_name='customers')
    op.create_unique_constraint('customers_phone_key', 'customers', ['phone'])
    op.create_unique_constraint('customers_document_number_key', 'customers', ['document_number'])
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('customers', 'total_spent',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'total_packages_delivered',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'total_packages_received',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('customers', 'is_vip',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('customers', 'preferred_language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'es'::character varying"))
    op.alter_column('customers', 'address_country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'Colombia'::character varying"))
    op.create_table('package_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('package_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('previous_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('additional_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('observations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='package_history_pkey')
    )
    op.drop_table('report_schedules')
    op.drop_table('reports')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_rates_rate_type'), table_name='rates')
    op.drop_index(op.f('ix_rates_is_active'), table_name='rates')
    op.drop_table('rates')
    op.drop_table('dashboard_metrics')
    # ### end Alembic commands ###
